### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by MidasLamb** [MidasLamb/Pomodoro#1]
##Timer

- [ ] Redraw the clock back to previous tick instead of to exact time.

##Data Visualisation

- [ ] Make ticks per day.
- [ ] Add more visualisations.
